### ISSUE TITLE
Module issue while using QnAMakerSimpleBot

### ISSUE THREAD

**Issue by rjgmail88** [Microsoft/BotBuilder-CognitiveServices#113]
I am using example code mentioned bellow with my V3 BOT and getting following error on VS code console. Am I missing any required dependancies ? 

Code:- same as provided  [here(https://github.com/Microsoft/BotBuilder-CognitiveServices/blob/master/Node/samples/QnAMaker/QnAMakerSimpleBot/app.js)

Error:- 
```
/usr/local/bin/node --inspect-brk=9200 app.js 
Debugger listening on ws://{}/{}
Debugger attached.
module.js:540
    throw err;
    ^

Error: Cannot find module 'sleep-promise'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/QnAMakerSimpleBot/node_modules/cognitive-services/dist/language/languageUnderstanding.js:13:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/QnAMakerSimpleBot/node_modules/cognitive-services/dist/index.js:26:28)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/QnAMakerSimpleBot/app.js:21:25)
    at Module._compile (module.js:640:14)
Waiting for the debugger to disconnect...
Error: Cannot find module 'sleep-promise'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/QnAMakerSimpleBot/node_modules/cognitive-services/dist/language/languageUnderstanding.js:13:20)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/QnAMakerSimpleBot/node_modules/cognitive-services/dist/index.js:26:28)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/QnAMakerSimpleBot/app.js:21:25)
    at Module._compile (module.js:640:14)

```

**Comment by stevengum97** [comment]
@rjgmail88 I think you're using the wrong module... It looks like you're using `cognitive-services` when you should be using [`botbuilder-cognitiveservices`](https://www.npmjs.com/package/botbuilder-cognitiveservices). Try installing the correct package via this command:

```bash
npm i botbuilder-cognitiveservices
```

**Comment by rjgmail88** [comment]
Looks like it worked. At least I'm able to build the project. Can you confirm if following is the correct way to load cognitiveservices object ?

```
var cognitiveservices = require('./node_modules/botbuilder-cognitiveservices/lib/botbuilder-cognitiveservices');
```

**Comment by snaxxi** [comment]
You should not load modules with full path. 

`var cognitiveservices = require('botbuilder-cognitiveservices');`

**Comment by rjgmail88** [comment]
The reason I am loading by full path is because in sample QnA code mentioned above has it the same way. Usually, i load by juts package name but in this package’s case it gives some dependancy issue.

**Comment by stevengum** [comment]
The entire path is just for the samples inside this repo; for any other case you will most likely just be using what @snaxxi put:

```js
var cognitiveservices = require('botbuilder-cognitiveservices');
```
