### ISSUE TITLE
Integral sample doesn't work

### ISSUE THREAD

**Issue by z2z** [microsoft/BotBuilder-CognitiveServices#80]
I am trying to demo, run https://github.com/Microsoft/BotBuilder-CognitiveServices/tree/master/Node/samples/Integral

```
D:\workspace\BotBuilder-CognitiveServices-master\Node\samples\Integral>node app.js
D:\workspace\BotBuilder-CognitiveServices-master\Node\samples\LuisActionBinding\time.js:11
builtInType: cognitiveservices.LuisBuiltInTypes.Geography.City
^

TypeError: Cannot read property 'Geography' of undefined
at Object.<anonymous> (D:\workspace\BotBuilder-CognitiveServices-master\Node\samples\LuisActionBinding\time.js:11:60)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (D:\workspace\BotBuilder-CognitiveServices-master\Node\samples\LuisActionBinding\all.js:3:13)
at Module._compile (module.js:570:32)
```
node -v
v6.12.2

npm -v
3.10.10

**Comment by cleemullins** [comment]
Thank you for opening an issue against the Bot Framework Cognitive Services repo. As part of the Bot Framework v4 release, we’ve moved all the Luis and QnA work to [platform SDK repo](https://github.com/Microsoft/botframework-sdk). We will continue to support and offer maintenance updates via this repo.
 
From now on, https://github.com/Microsoft/botframework-sdk repo will be used as hub, with pointers to all the different SDK languages, tools and samples repos.
 
As part of this restructuring, we are closing all tickets in this repo.
 
For defects or feature requests, please create a new issue in the Bot Framework repo found here:
https://github.com/Microsoft/botframework-sdk/issues

For product behavior, how-to, or general understanding questions, please use Stackoverflow.
https://stackoverflow.com/search?q=bot+framework

Thank you.
 
The Bot Framework Team
